### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by MjelleLab** [biobakery/MetaPhlAn#110]
Hi,
I  get an error running hamann, related to metaphlan, please see below. 

**I use the following bowtie2:**

_64-bit
Built on 
Sat Jun  6 20:17:22 UTC 2020
Compiler: gcc version 7.5.0 (crosstool-NG 1.24.0.123_1667d2b) 
Options: -O3 -msse2 -funroll-loops -g3 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /local/home/robinm/miniconda2/envs/biobakery3/include -fdebug-prefix-map=/opt/conda/conda-bld/bowtie2_1591474367590/work=/usr/local/src/conda/bowtie2-2.4.1 -fdebug-prefix-map=/local/home/robinm/miniconda2/envs/biobakery3=/usr/local/src/conda-prefix -DPOPCNT_CAPABILITY -DWITH_TBB -std=c++11 -DNO_SPINLOCK -DWITH_QUEUELOCK=1
Sizeof {int, long, long long, void*, size_t, off_t}: {4, 8, 8, 8, 8, 8}_

**This is my error:**

(biobakery3) username@havpryd:~/ncbi/dbGaP-20066/sra$ humann --threads 20 -i test2.fastq --protein-database uniref/uniref/ -o testout

Output files will be written to: /local/home/username/ncbi/dbGaP-20066/sra/testout
Removing spaces from identifiers in input file ...

Running metaphlan ........

CRITICAL ERROR: Error executing: /local/home/username/miniconda2/envs/biobakery3/bin/metaphlan /local/home/username/ncbi/dbGaP-20066/sra/testout/test2_humann_temp/tmpafwourve/tmpj1r25wbh -t rel_ab -o /local/home/username/ncbi/dbGaP-20066/sra/testout/test2_humann_temp/test2_metaphlan_bugs_list.tsv --input_type fastq --bowtie2out /local/home/username/ncbi/dbGaP-20066/sra/testout/test2_humann_temp/test2_metaphlan_bowtie2.txt --nproc 20

Error message returned from metaphlan :
Use of uninitialized value $bt2_args[2] in join or string at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[3] in join or string at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 423.
Use of uninitialized value $_[2] in string eq at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 360.
Use of uninitialized value $_[3] in string eq at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 360.
Use of uninitialized value in exists at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 81.
Use of uninitialized value in exists at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[2] in join or string at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[3] in join or string at /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2 line 459.
Error reading _ebwt[] array: no more data
Error: Encountered internal Bowtie 2 exception (#1)
Command: /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2-align-s --wrapper basic-0 --quiet --very-sensitive -x /local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901 -p 20 --passthrough -U - 
(ERR): bowtie2-align exited with value 1
Traceback (most recent call last):
  File "/local/home/username/miniconda2/envs/biobakery3/bin/read_fastx.py", line 10, in <module>
    sys.exit(main())
  File "/local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 155, in main
    nreads += read_and_write_raw(f, opened=False, min_len=min_len)
  File "/local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 119, in read_and_write_raw
    nreads = read_and_write_raw_int(inf, min_len=min_len)
  File "/local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 98, in read_and_write_raw_int
    _ = sys.stdout.write(print_record(description, sequence, qual, fmt))
BrokenPipeError: [Errno 32] Broken pipe

**Comment by fbeghini** [comment]
It looks like bowtie2 is not working correctly. Can you inspect the file and check if it is not truncated? Also, can you run bowtie2 and map the same file against the metaphlan database? It should be located in `/local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases`

**Comment by MjelleLab** [comment]
(biobakery3) robinm@havpryd:~/ncbi/dbGaP-20066/sra$ bowtie2 -x /local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901 -q test.fastq -S test.sam
Error reading _ebwt[] array: no more data
Error: Encountered internal Bowtie 2 exception (#1)
Command: /local/home/username/miniconda2/envs/biobakery3/bin/bowtie2-align-s --wrapper basic-0 -x /local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901 -q -S test.sam test.fastq 
(ERR): bowtie2-align exited with value 1

**Comment by fbeghini** [comment]
How many reads the fastq has?

**Comment by MjelleLab** [comment]
Its 40 000 lines, or 10000 reads. Just the head -40000 of a random fastq file.

**Comment by fbeghini** [comment]
You can download the file. The fastq is OK, maybe the built index is corrupted. Can you inspect the bt2 indexes with `bowtie2-inspect /local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/mpa_v30_CHOCOPhlAn_201901 > /dev/null` ? 

Can you also paste here the content of the `/local/home/username/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/` folder?

**Comment by MjelleLab** [comment]
bowtie2-inspect printed all the fasta sequences and look OK. 


(biobakery3) robinm@havpryd:~/ncbi/dbGaP-20066/sra$ ls -l /local/home/robinm/miniconda2/envs/biobakery3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/
total 3375085
-rw-r--r-- 1 robinm robinm       3526 Jun 22 15:15 file_list.txt
-rw-r--r-- 1 robinm robinm         26 Jun 22 15:15 mpa_latest
-rw-r--r-- 1 robinm robinm         63 Jun 22 15:24 mpa_mpa_v30_CHOCOPhlAn_201901.md5
-rw-r--r-- 1 robinm robinm  384522240 Jun 22 15:24 mpa_mpa_v30_CHOCOPhlAn_201901.tar
-rw-r--r-- 1 robinm robinm  629658510 Jun 22 15:34 mpa_v30_CHOCOPhlAn_201901.1.bt2
-rw-r--r-- 1 robinm robinm  299363612 Jun 22 15:34 mpa_v30_CHOCOPhlAn_201901.2.bt2
-rw-r--r-- 1 robinm robinm   10316222 Jun 22 15:25 mpa_v30_CHOCOPhlAn_201901.3.bt2
-rw-r--r-- 1 robinm robinm  299363608 Jun 22 15:25 mpa_v30_CHOCOPhlAn_201901.4.bt2
-rw-r--r-- 1 robinm robinm 1427174368 Jun 22 15:25 mpa_v30_CHOCOPhlAn_201901.fna
-rw-rw-r-- 1 robinm robinm  358461323 May 12 13:25 mpa_v30_CHOCOPhlAn_201901.fna.bz2
-rw-rw-r-- 1 robinm robinm   26058383 May 12 13:31 mpa_v30_CHOCOPhlAn_201901.pkl
-rw-r--r-- 1 robinm robinm   18276352 Jun 22 15:35 mpa_v30_CHOCOPhlAn_201901.rev.1.bt2
-rw-r--r-- 1 robinm robinm          0 Jun 22 15:34 mpa_v30_CHOCOPhlAn_201901.rev.2.bt2

**Comment by MjelleLab** [comment]
I already had problems with the bowtie version when running humann, so I removed the bowtie-test line from the humann python script:

#utilities.check_software_version("bowtie2", config.bowtie2_version).

**Comment by fbeghini** [comment]
It looks like that one file of the index is empty (mpa_v30_CHOCOPhlAn_201901.rev.2.bt2), it may worth trying removing all the `.bt2` files and re-build the index starting from the `fna`.

The warning bowtie2 prompts (Use of uninitialized value [...]) are not affecting the results, you can downgrade the package to 2.3.5.1 if you want

**Comment by MjelleLab** [comment]
In seem to run now: 


(biobakery3) username@server:~/ncbi/dbGaP-20066/sra$ humann --threads 20 -i test2.fastq --protein-database uniref/uniref/ -o testout
Output files will be written to: /local/home/username/ncbi/dbGaP-20066/sra/testout
Removing spaces from identifiers in input file ...


Running metaphlan ........


Total species selected from prescreen: 0

Selected species explain 0.00% of predicted community composition



No species were selected from the prescreen.
Because of this the custom ChocoPhlAn database is empty.
This will result in zero species-specific gene families and pathways.



Running diamond ........


Aligning to reference database: uniref90_201901.dmnd

	Total bugs after translated alignment: 1
unclassified: 162 hits

Total gene families after translated alignment: 8

Unaligned reads after translated alignment: 85.8000000000 %


Computing gene families ...

Computing pathways abundance and coverage ...

Output files created: 
/local/home/username/ncbi/dbGaP-20066/sra/testout/test2_genefamilies.tsv
/local/home/username/ncbi/dbGaP-20066/sra/testout/test2_pathabundance.tsv
/local/home/username/ncbi/dbGaP-20066/sra/testout/test2_pathcoverage.tsv

**Comment by nick-youngblut** [comment]
I'm getting a similar error:

```
Use of uninitialized value $bt2_args[2] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[3] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 423.
Use of uninitialized value $_[2] in string eq at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 360.
Use of uninitialized value $_[3] in string eq at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 360.
Use of uninitialized value in exists at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 81.
Use of uninitialized value in exists at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[2] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[3] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/bowtie2 line 459.
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1060, in main
    pars['tax_lev']+"__" if pars['tax_lev'] != 'a' else None )
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 733, in relative_abundances
    tot_ab += clade.compute_abundance()
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/e7d9f6fa/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 531, in compute_abundance
    ext_clade = self.taxa2clades[ext]
KeyError: 'GCA_900110295'
```

Reprex:

```
metaphlan --install --bowtie2db /ebio/abt3_projects/databases_no-backup/metaphlan3/201901/
metaphlan --nproc 8 --input_type fastq -o tmp/metaphlan3 --bowtie2db /ebio/abt3_projects/databases_no-backup/metaphlan3/201901/  reads.fq
```

Conda env:

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
bcbio-gff                 0.6.6                      py_0    bioconda
biom-format               2.1.8            py37hc1659b7_0    conda-forge
biopython                 1.77             py37h8f50634_0    conda-forge
blast                     2.9.0           pl526he19e7b1_5    bioconda
boost-cpp                 1.70.0               h8e57a91_2    conda-forge
bowtie2                   2.4.1            py37h4ef193e_2    bioconda
brotlipy                  0.7.0           py37h8f50634_1000    conda-forge
bx-python                 0.8.9            py37h5266303_0    bioconda
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cmseq                     1.0                pyh5ca1d4c_0    bioconda
cryptography              2.9.2            py37hb09aad4_0    conda-forge
curl                      7.71.0               he644dc0_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
dendropy                  4.4.0                      py_1    bioconda
diamond                   0.9.36               h56fc30b_0    bioconda
entrez-direct             13.3            pl526h375a9b1_0    bioconda
expat                     2.2.9                he1b5a44_2    conda-forge
fasttree                  2.1.10               h14c3975_3    bioconda
freetype                  2.10.2               he06d7ca_0    conda-forge
future                    0.18.2           py37hc8dfbb8_1    conda-forge
glpk                      4.65              he80fd80_1002    conda-forge
gmp                       6.2.0                he1b5a44_2    conda-forge
h5py                      2.10.0          nompi_py37h90cd8ad_103    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_100    conda-forge
htslib                    1.9                  h4da6232_3    bioconda
humann                    3.0.0.alpha.3    py37h83b1523_0    biobakery
icu                       64.2                 he1b5a44_1    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
iqtree                    2.0.3                h176a8bc_0    bioconda
kiwisolver                1.2.0            py37h99015e2_0    conda-forge
krb5                      1.17.1               hfafb76e_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.0               hcdd3856_0    conda-forge
libdeflate                1.6                  h516909a_0    conda-forge
libedit                   3.1.20191231         h46ee950_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
liblapack                 3.8.0               17_openblas    conda-forge
libopenblas               0.3.10               h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libssh2                   1.9.0                hab1572f_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
mafft                     7.470                h516909a_0    bioconda
matplotlib-base           3.2.2            py37h30547a4_0    conda-forge
metaphlan                 3.0.1              pyh5ca1d4c_0    bioconda
msgpack-python            1.0.0            py37h99015e2_1    conda-forge
muscle                    3.8.1551             hc9558a2_5    bioconda
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.18.5           py37h8960a57_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pandas                    1.0.5            py37h0da4684_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda
perl-archive-tar          2.32                    pl526_0    bioconda
perl-base                 2.23                    pl526_1    bioconda
perl-business-isbn        3.004                   pl526_0    bioconda
perl-business-isbn-data   20140910.003            pl526_0    bioconda
perl-carp                 1.38                    pl526_3    bioconda
perl-common-sense         3.74                    pl526_2    bioconda
perl-compress-raw-bzip2   2.087           pl526he1b5a44_0    bioconda
perl-compress-raw-zlib    2.087           pl526hc9558a2_0    bioconda
perl-constant             1.33                    pl526_1    bioconda
perl-data-dumper          2.173                   pl526_0    bioconda
perl-digest-hmac          1.03                    pl526_3    bioconda
perl-digest-md5           2.55                    pl526_0    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-encode-locale        1.05                    pl526_6    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.002001                pl526_0    bioconda
perl-extutils-makemaker   7.36                    pl526_1    bioconda
perl-file-listing         6.04                    pl526_1    bioconda
perl-file-path            2.16                    pl526_0    bioconda
perl-file-temp            0.2304                  pl526_2    bioconda
perl-html-parser          3.72            pl526h6bb024c_5    bioconda
perl-html-tagset          3.20                    pl526_3    bioconda
perl-html-tree            5.07                    pl526_1    bioconda
perl-http-cookies         6.04                    pl526_0    bioconda
perl-http-daemon          6.01                    pl526_1    bioconda
perl-http-date            6.02                    pl526_3    bioconda
perl-http-message         6.18                    pl526_0    bioconda
perl-http-negotiate       6.01                    pl526_3    bioconda
perl-io-compress          2.087           pl526he1b5a44_0    bioconda
perl-io-html              1.001                   pl526_2    bioconda
perl-io-socket-ssl        2.066                   pl526_0    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-json                 4.02                    pl526_0    bioconda
perl-json-xs              2.34            pl526h6bb024c_3    bioconda
perl-libwww-perl          6.39                    pl526_0    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-lwp-mediatypes       6.04                    pl526_0    bioconda
perl-lwp-protocol-https   6.07                    pl526_4    bioconda
perl-mime-base64          3.15                    pl526_1    bioconda
perl-mozilla-ca           20180117                pl526_1    bioconda
perl-net-http             6.19                    pl526_0    bioconda
perl-net-ssleay           1.88            pl526h90d6eec_0    bioconda
perl-ntlm                 1.09                    pl526_4    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.75            pl526h14c3975_1    bioconda
perl-scalar-list-utils    1.52            pl526h516909a_0    bioconda
perl-socket               2.027                   pl526_1    bioconda
perl-storable             3.15            pl526h14c3975_0    bioconda
perl-test-requiresinternet 0.05                    pl526_0    bioconda
perl-time-local           1.28                    pl526_1    bioconda
perl-try-tiny             0.30                    pl526_1    bioconda
perl-types-serialiser     1.0                     pl526_2    bioconda
perl-uri                  1.76                    pl526_0    bioconda
perl-www-robotrules       6.02                    pl526_3    bioconda
perl-xml-namespacesupport 1.12                    pl526_0    bioconda
perl-xml-parser           2.44_01         pl526ha1d75be_1002    conda-forge
perl-xml-sax              1.02                    pl526_0    bioconda
perl-xml-sax-base         1.09                    pl526_0    bioconda
perl-xml-sax-expat        0.51                    pl526_3    bioconda
perl-xml-simple           2.25                    pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
phylophlan                3.0                        py_5    bioconda
pigz                      2.3.4                hed695b0_1    conda-forge
pip                       20.1.1                     py_1    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py37hc501bad_0    bioconda
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6           cpython_h8356626_6    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-lzo                1.12            py37h81344f2_1001    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.1             pyh9f0ad1d_0    conda-forge
raxml                     8.2.12               h14c3975_1    bioconda
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
samtools                  1.9                 h10a08f8_12    bioconda
scipy                     1.5.0            py37ha3d9a3c_0    conda-forge
seaborn                   0.10.1                        1    conda-forge
seaborn-base              0.10.1                     py_1    conda-forge
seqkit                    0.12.1                        0    bioconda
setuptools                47.3.1           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.32.3               hcee41ef_0    conda-forge
statsmodels               0.11.1           py37h8f50634_2    conda-forge
tbb                       2020.1               hc9558a2_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
trimal                    1.4.1                h6bb024c_3    bioconda
urllib3                   1.25.9                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

**Comment by fbeghini** [comment]
Okay, I've been correcting the GCA accessions for some species and probably I've missed that. I've re-uploded the tar with the fixed pkl database, you can download it from [here](https://www.dropbox.com/sh/7qze7m7g9fe2xjg/AADlxibskzbPHPoDl6S-FyKka/mpa_v30_CHOCOPhlAn_201901.tar?dl=1) and replace just the pkl file

**Comment by nick-youngblut** [comment]
Thanks for the quick response! I tried replacing the pkl file, but I'm still getting: 

```
Use of uninitialized value $bt2_args[2] in join or string at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[3] in join or string at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 423.
Use of uninitialized value $_[2] in string eq at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 360.
Use of uninitialized value $_[3] in string eq at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 360.
Use of uninitialized value in exists at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 81.
Use of uninitialized value in exists at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[2] in join or string at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[3] in join or string at /ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/bowtie2 line 459.

Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1060, in main
    pars['tax_lev']+"__" if pars['tax_lev'] != 'a' else None )
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 733, in relative_abundances
    tot_ab += clade.compute_abundance()
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 519, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/humann3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 531, in compute_abundance
    ext_clade = self.taxa2clades[ext]
KeyError: 'GCA_003012055'
```

It's a bit troubling that so many errors can be reported before the script dies. Maybe more "check if OK | exit" are needed?

**Comment by fbeghini** [comment]
The file was not fully synched with dropbox, now should be ok. The cascade in the traceback is due to the fact that the relative abundance is compute recursively

**Comment by nick-youngblut** [comment]
I've re-downloaded the database, and I still get the warnings:

```
Use of uninitialized value $bt2_args[2] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 423.
Use of uninitialized value $bt2_args[3] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 423.
Use of uninitialized value $_[2] in string eq at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 360.
Use of uninitialized value $_[3] in string eq at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 360.
Use of uninitialized value in exists at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 81.
Use of uninitialized value in exists at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 81.
Use of uninitialized value $bt2_args[2] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 459.
Use of uninitialized value $bt2_args[3] in join or string at /ebio/abt3_projects/software/dev/llmgp/.snakemake/conda/7402770c/bin/bowtie2 line 459.
WARNING: The metagenome profile contains clades that represent multiple species merged into a single representant.
An additional column listing the merged species is added to the MetaPhlAn output.
```

...but metaphlan finished without an error! Thanks for your help with this.

**Comment by fbeghini** [comment]
The errors are raised by Bowtie2, the latest build on bioconda has bugs,
you can downgrade to the previous one

----

Francesco Beghini

PhD Student


Lab. of Computational Metagenomics

Department of Cellular, Computational and Integrative Biology - CIBIO

University of Trento
Via Sommarive 9, 38123 Trento, Italy

Il Gio 2 Lug 2020, 20:15 Nick Youngblut <notifications@github.com> ha
scritto:
