### ISSUE TITLE
Wrong file name in metaphlan.py

### ISSUE THREAD

**Issue by anschue** [biobakery/MetaPhlAn#111]
I run into trouble when using metaphlan3 the first time during the installation of the databases (see Error log below). Installation of metaphlan was via anaconda on CentOS7. I could solve the problem by removing 4 times a leading "mpa_" in the metaphlan.py file.

`metaphlan --input fasta test.fasta > profile1`

> Downloading MetaPhlAn database
Please note due to the size this might take a few minutes

> File /home/USER/anaconda3/envs/metap/lib/python3.6/site-packages/metaphlan/metaphlan_databases/file_list.txt already present!
> Traceback (most recent call last):
  File "/home/USER/anaconda3/envs/metap/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/home/USER/anaconda3/envs/metap/lib/python3.6/site-packages/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/home/USER/anaconda3/envs/metap/lib/python3.6/site-packages/metaphlan/metaphlan.py", line 610, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "/home/USER/anaconda3/envs/metap/lib/python3.6/site-packages/metaphlan/metaphlan.py", line 463, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
KeyError: 'mpa_mpa_v30_CHOCOPhlAn_201901.tar'

**Comment by fbeghini** [comment]
This has been already resolved, see #109
