### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by Caelyn996** [biobakery/MetaPhlAn#135]
Hi,
When I used the code "metaphlan e1_1.fastq,e1_2.fastq --bowtie2out e1.bowtie2.bz2 --nproc 6 --bowtie2db ~/database/metaphlan_databases/ -x mpa_v30_CHOCOPhlAn_201901 --input_type fastq -o e1_profiled.txt" to run metaphlan 3.0.5, I got the error below. Is there anyone who know how to fix it? Thanks so much!

Traceback (most recent call last):
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1072, in main
    pars['tax_lev']+"__" if pars['tax_lev'] != 'a' else None )
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 739, in relative_abundances
    tot_ab += clade.compute_abundance()
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in compute_abundance
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 523, in <listcomp>
    sum_ab = sum([c.compute_abundance() for c in self.children.values()])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 589, in compute_abundance
    wnreads = sorted([(float(n)/(r-self.avg_read_length+1),(r - self.avg_read_length+1) ,n) for r,n in rat_nreads], key=lambda x:x[0])
  File "/gpfs/share/home/1801111740/miniconda3/envs/biobakery/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 589, in <listcomp>
    wnreads = sorted([(float(n)/(r-self.avg_read_length+1),(r - self.avg_read_length+1) ,n) for r,n in rat_nreads], key=lambda x:x[0])
ZeroDivisionError: float division by zero

**Comment by khillion** [comment]
Hi, just to let you know that I am having the same issue with my dataset.

I had no issue with the test dataset for StrainPhlan: https://github.com/biobakery/MetaPhlAn/wiki/StrainPhlAn-3.0#usage

### Tool information

* MetaPhlAn version 3.0.5 (10 Nov 2020)

Thanks

**Comment by fbeghini** [comment]
Can you try with version 3.0.6? I have fixed this with the latest update

**Comment by khillion** [comment]
Hi Francesco, I have just tried with the latest version. Unfortunately, there has been some changes in the code that require access to the internet when checking for databases line 258 of the `__init__.py` file at the root of metaphlan.

Since I am running it on a HPC without any access to the internet, it is no longer working. Do you think it would be possible to keep metaphlan entirely operational without internet access?

Thank you very much for your quick answer.

**Comment by fbeghini** [comment]
Yes, if you already have the database downloaded and built, you can execute MetaPhlAn with the `--index mpa_v30_CHOCOPhlAn_201901` and this will skip the check for a new version

**Comment by khillion** [comment]
Thank you very much, I missed that option, it works now from my side

**Comment by Caelyn996** [comment]
> Can you try with version 3.0.6? I have fixed this with the latest update

Thanks a lot! It works well now!

**Comment by gregmcc97** [comment]
Hi, I am getting this same issue for one of my datasets. I am using version 3.0.6, works fine for 5 other sets of reads but one set gives this error:

`Traceback (most recent call last):
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/bin/read_fastx.py", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 155, in main
    f_nreads, f_avg_read_length = read_and_write_raw(f, opened=False, min_len=min_len)
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 118, in read_and_write_raw
    nreads, avg_read_length = read_and_write_raw_int(inf, min_len=min_len)
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 110, in read_and_write_raw_int
    avg_read_length /= nreads
ZeroDivisionError: division by zero
`

**Comment by gregmcc97** [comment]
Hi, I am getting this same issue for one of my datasets. I am using version 3.0.6, works fine for 5 other sets of reads but one set gives this error:

Traceback (most recent call last):
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/bin/read_fastx.py", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 155, in main
    f_nreads, f_avg_read_length = read_and_write_raw(f, opened=False, min_len=min_len)
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 118, in read_and_write_raw
    nreads, avg_read_length = read_and_write_raw_int(inf, min_len=min_len)
  File "/home/ubuntu/sdb/miniconda3/envs/metaphlan3/lib/python3.7/site-packages/metaphlan/utils/read_fastx.py", line 110, in read_and_write_raw_int
    avg_read_length /= nreads
ZeroDivisionError: division by zero

**Comment by fbeghini** [comment]
Can you check if the file is OK, how many reads has it, and the minimum,
maximum value for the read length?
----
*Francesco Beghini*
*PhD Student*

Lab. of Computational Metagenomics
Department of Cellular, Computational and Integrative Biology - CIBIO
University of Trento
Via Sommarive 9, 38123 Trento, Italy

ᐧ

**Comment by gregmcc97** [comment]
> Can you check if the file is OK, how many reads has it, and the minimum, maximum value for the read length?

Hi, thanks for the reply!

The files seem fine on fastQC. Both the read 1 and read 2 files have 183,480,501 reads, and minimum length 30 bp, maximum length 66 bp.

**Comment by fbeghini** [comment]
> minimum length 30 bp, maximum length 66 bp.

They are quite short. By default, MetaPhlAn filters reads shorter than 70bp, so no reads were retained by read_fastx. You can use `--read_min_len 29` to include all your reads

**Comment by gregmcc97** [comment]
Oh I see, thank you! Working now with `--read_min_len 29` thanks!
