### ISSUE TITLE
Problem with pcikle protocol (current conda install version)

### ISSUE THREAD

**Issue by kescobo** [biobakery/MetaPhlAn#70]
Trying to run the tutorial file:

```
$ metaphlan2.py input/SRS014476-Supragingival_plaque.fasta.gz --input_type fasta > output/SRS014476-Supragingival_plaque_profile.txt
Traceback (most recent call last):
  File "/opt/miniconda3/envs/biobakery2/bin/metaphlan2.py", line 1388, in <module>
    metaphlan2()
  File "/opt/miniconda3/envs/biobakery2/bin/metaphlan2.py", line 1217, in metaphlan2
    mpa_pkl = pickle.load( a )
  File "/opt/miniconda3/envs/biobakery2/lib/python2.7/pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "/opt/miniconda3/envs/biobakery2/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/opt/miniconda3/envs/biobakery2/lib/python2.7/pickle.py", line 892, in load_proto
    raise ValueError, "unsupported pickle protocol: %d" % proto
ValueError: unsupported pickle protocol: 3
```

This from the current `conda` download obtained by doing `conda install -c bioconda metaphlan2`. If instead I do `conda install -c bioconda/label/cf201901 metaphlan2`, which give me version 2.7.8, and doesn't seem to have this problem.

**Comment by fbeghini** [comment]
Hi Kevin,
I've uploaded a new bioconda recipe which includes the latest MetaPhlAn 3, you can install it by doing `conda install -c bioconda metaphlan=3` .

**Comment by kescobo** [comment]
Alright, I'll give this a shot, thanks!
