### ISSUE TITLE
download_file_name mismatch

### ISSUE THREAD

**Issue by Scelta** [biobakery/MetaPhlAn#72]
I found the script seems added redundant "map_" in front of download file name.  
Change `"mpa_" + download_file_name + ".tar"` to ` download_file_name + ".tar"` in [metaphlan.py#L462~L468](https://github.com/biobakery/MetaPhlAn/blob/0228b272a337fe8416607725956134ec91d3662b/metaphlan/metaphlan.py#L462)  solved my problem.

ps: I installed it on an internet restrict HPC system so I hacked the urls to a local path.
```
metaphlan.py --install

Downloading file:///ldfs/*/share/database/biobakery/metaphlan3/file_list_local.txt
Downloading file of size: 0.00 MB
0.01 MB 243.66 %   0.77 MB/sec  0 min -0 sec
Downloading file:///ldfs/*/share/database/biobakery/metaphlan3/dropbox/mpa_latest
Downloading file of size: 0.00 MB
0.01 MB 31507.69 %   9.82 MB/sec  0 min -0 sec
Downloading MetaPhlAn database
Please note due to the size this might take a few minutes

File /ldfs/*/SHR/opt/MetaPhlAn/metaphlan/metaphlan_databases/file_list.txt already present!
Traceback (most recent call last):
  File "/ldfs/*/SHR/opt/MetaPhlAn/metaphlan/metaphlan.py", line 1465, in <module>
    main()
  File "/ldfs/*/SHR/opt/MetaPhlAn/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "/ldfs/*/SHR/opt/MetaPhlAn/metaphlan/metaphlan.py", line 610, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "/ldfs/*/SHR/opt/MetaPhlAn/metaphlan/metaphlan.py", line 463, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
KeyError: 'mpa_mpa_v30_CHOCOPhlAn_201901.tar'
```

**Comment by fbeghini** [comment]
Hi Chao, thank you for reporting this. I'll push the fix ASAP.
