### ISSUE TITLE
KeyError while downloading database

### ISSUE THREAD

**Issue by nahanoo** [biobakery/MetaPhlAn#81]
Hi everyone,

Congrats on the new release!

While downloading MetaPhlAn database I'm getting a KeyError.

```
File /miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan_databases/file_list.txt already present!
Traceback (most recent call last):
  File "miniconda3/bin/metaphlan", line 10, in <module>
    sys.exit(main())
  File "miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 1187, in main
    pars['index'] = check_and_install_database(pars['index'], pars['bowtie2db'], pars['bowtie2_build'], pars['nproc'], pars['force_download'])
  File "miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 610, in check_and_install_database
    download_unpack_tar(FILE_LIST, index, bowtie2_db, bowtie2_build, nproc)
  File "miniconda3/lib/python3.7/site-packages/metaphlan/metaphlan.py", line 463, in download_unpack_tar
    url_tar_file = ls_f["mpa_" + download_file_name + ".tar"]
KeyError: 'mpa_mpa_v296_CHOCOPhlAn_201901.tar'
```

Let me know if there is something more I can provide which helps debugging.

Cheers

**Comment by nahanoo** [comment]
Sorry folks, just saw that this was posted already.

I'll work through issue #78.
